name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: package
    strategy:
      matrix:
        os: [macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install
        run: |
          yarn
      - name: Build
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}